# Generated by Django 5.2.5 on 2025-10-01 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=100)),
                ('subject', models.TextField(blank=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('recipient_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(default=list)),
                ('bcc_emails', models.JSONField(default=list)),
                ('sent_date', models.DateTimeField(db_index=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_count', models.IntegerField(default=0)),
                ('labels', models.JSONField(default=list)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('attachment_id', models.CharField(max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gmail_integration.emailmessage')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('encrypted_credentials', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('total_emails', models.IntegerField(default=0)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Account',
                'verbose_name_plural': 'Gmail Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='gmail_integration.gmailaccount'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emails_processed', models.IntegerField(default=0)),
                ('emails_added', models.IntegerField(default=0)),
                ('emails_updated', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('gmail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='gmail_integration.gmailaccount')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['gmail_account', 'sent_date'], name='gmail_integ_gmail_a_79a8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['sender_email', 'sent_date'], name='gmail_integ_sender__344624_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['gmail_id'], name='gmail_integ_gmail_i_3472c8_idx'),
        ),
    ]
