# Generated by Django 5.2.5 on 2025-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], max_length=20),
        ),
    ]
