# Generated by Django 5.2.5 on 2025-10-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0002_alter_synclog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Sync Started'), ('fetch', 'Fetching Batch'), ('process', 'Processing Emails'), ('progress', 'Progress Update'), ('complete', 'Batch Complete'), ('cancel', 'Sync Cancelled'), ('error', 'Error Occurred'), ('finish', 'Sync Finished')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emails_processed', models.IntegerField(default=0)),
                ('emails_added', models.IntegerField(default=0)),
                ('emails_updated', models.IntegerField(default=0)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='gmail_integration.synclog')),
            ],
            options={
                'verbose_name': 'Sync History Event',
                'verbose_name_plural': 'Sync History Events',
                'ordering': ['timestamp'],
            },
        ),
    ]
