# Generated by Django 5.2.5 on 2025-10-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0003_synchistoryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='has_invoice',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='invoice_confidence',
            field=models.CharField(choices=[('high', 'High - Multiple indicators'), ('medium', 'Medium - Some indicators'), ('low', 'Low - Weak indicators'), ('none', 'None - No indicators')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='invoice_keywords_found',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['has_invoice', 'sent_date'], name='gmail_integ_has_inv_b142fc_idx'),
        ),
    ]
