# Generated by Django 5.2.5 on 2025-10-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0004_emailmessage_has_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='classification_label',
            field=models.CharField(blank=True, help_text="Final classification label (e.g., 'daycare_invoice', 'not_invoice')", max_length=50),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='classified_at',
            field=models.DateTimeField(blank=True, help_text='When this email was classified', null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_classified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this email has been classified by AI (confirmed or auto-confirmed)'),
        ),
    ]
