# Generated by Django 5.2.5 on 2025-09-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name (e.g., Groceries, Salary, Entertainment)', max_length=100)),
                ('icon', models.CharField(default='bi-folder', help_text='Bootstrap icon class (e.g., bi-cart, bi-house)', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI display', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, to='household_budget.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('family', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_payee', models.CharField(help_text='Who you paid or received money from', max_length=200)),
                ('date', models.DateField(help_text='Transaction date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], help_text='Type of transaction', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('category', models.ForeignKey(blank=True, help_text='Transaction category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='household_budget.category')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['family', 'date'], name='household_b_family__7f216f_idx'), models.Index(fields=['family', 'transaction_type'], name='household_b_family__f0f26f_idx'), models.Index(fields=['family', 'category'], name='household_b_family__48aee2_idx')],
            },
        ),
    ]
