# Generated by Django 5.2.5 on 2025-09-04 02:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Budget name (e.g., '2024 Family Budget')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Budget description')),
                ('start_date', models.DateField(help_text='Budget start date')),
                ('end_date', models.DateField(blank=True, help_text='Budget end date (leave blank for ongoing)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this budget is currently active')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name (e.g., Salary, Groceries, Utilities)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this is income or expense category', max_length=10)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI display', max_length=7)),
                ('is_essential', models.BooleanField(default=False, help_text='Whether this is an essential category (needs vs wants)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category for subcategories', null=True, on_delete=django.db.models.deletion.CASCADE, to='household_budget.budgetcategory')),
            ],
            options={
                'verbose_name': 'Budget Category',
                'verbose_name_plural': 'Budget Categories',
                'ordering': ['category_type', 'sort_order', 'name'],
                'unique_together': {('family', 'name', 'category_type')},
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Savings goal name (e.g., 'Emergency Fund', 'Vacation')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Goal description')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target amount to save', max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount saved', max_digits=10)),
                ('target_date', models.DateField(blank=True, help_text='Target date to achieve goal', null=True)),
                ('monthly_contribution', models.DecimalField(blank=True, decimal_places=2, help_text='Planned monthly contribution', max_digits=10, null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Goal priority (1 = highest)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this goal is active')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
            ],
            options={
                'verbose_name': 'Savings Goal',
                'verbose_name_plural': 'Savings Goals',
                'ordering': ['priority', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField(help_text='Date of transaction')),
                ('description', models.CharField(help_text='Transaction description', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], help_text='Type of transaction', max_length=10)),
                ('payee', models.CharField(blank=True, help_text='Who the transaction was with', max_length=100)),
                ('account', models.CharField(blank=True, help_text='Account used for transaction', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('receipt_image', models.ImageField(blank=True, help_text='Receipt image', null=True, upload_to='receipts/')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether transaction has been reconciled')),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number', max_length=100)),
                ('category', models.ForeignKey(blank=True, help_text='Budget category for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='household_budget.budgetcategory')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, help_text='Budgeted amount for this category', max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount spent/earned (auto-calculated from transactions)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Notes about this budget item')),
                ('budget', models.ForeignKey(help_text='Budget this item belongs to', on_delete=django.db.models.deletion.CASCADE, to='household_budget.budget')),
                ('category', models.ForeignKey(help_text='Budget category', on_delete=django.db.models.deletion.CASCADE, to='household_budget.budgetcategory')),
            ],
            options={
                'verbose_name': 'Budget Item',
                'verbose_name_plural': 'Budget Items',
                'ordering': ['category__category_type', 'category__sort_order', 'category__name'],
                'unique_together': {('budget', 'category')},
            },
        ),
    ]
