# Generated by Django 5.2.5 on 2025-09-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories that this payee/merchant is associated with', related_name='payees', to='bank.category'),
        ),
    ]
