# Generated by Django 5.2.5 on 2025-10-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', help_text='Whether this merchant is typically used for income or expenses', max_length=10),
        ),
    ]
