# Generated by Django 5.2.5 on 2025-09-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_basic', '0006_expense_category_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('both', 'Both Income & Expense')], default='expense', help_text='Whether this category applies to income, expenses, or both', max_length=10),
        ),
    ]
