# Generated by Django 5.2.5 on 2025-09-04 02:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the project', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this project is currently active')),
                ('client_name', models.CharField(blank=True, help_text='Client or company name for this project', max_length=200)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for this project', max_digits=8, null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this project', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
                'unique_together': {('family', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the work')),
                ('start_time', models.TimeField(help_text='Start time of work')),
                ('end_time', models.TimeField(help_text='End time of work')),
                ('break_duration', models.PositiveIntegerField(default=0, help_text='Break duration in minutes')),
                ('description', models.TextField(blank=True, help_text='Description of work performed')),
                ('is_billable', models.BooleanField(default=True, help_text='Whether this time entry is billable')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
                ('project', models.ForeignKey(help_text='Project this time entry belongs to', on_delete=django.db.models.deletion.CASCADE, to='timesheet.project')),
                ('user', models.ForeignKey(help_text='User this record belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
