# Generated by Django 5.2.5 on 2025-09-04 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the daycare provider', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Main contact person at the daycare', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Physical address of the daycare')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is currently active')),
                ('license_number', models.CharField(blank=True, help_text='Daycare license number', max_length=50)),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
            ],
            options={
                'verbose_name': 'Daycare Provider',
                'verbose_name_plural': 'Daycare Providers',
                'ordering': ['name'],
                'unique_together': {('family', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text="Child's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Child's last name", max_length=50)),
                ('date_of_birth', models.DateField(help_text="Child's date of birth")),
                ('start_date', models.DateField(blank=True, help_text='Date child started at current provider', null=True)),
                ('is_enrolled', models.BooleanField(default=True, help_text='Whether child is currently enrolled')),
                ('special_needs', models.TextField(blank=True, help_text='Any special needs or requirements')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact person', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20)),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
                ('provider', models.ForeignKey(blank=True, help_text='Current daycare provider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycare_invoices.daycareprovider')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('family', 'first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, help_text="Provider's invoice number", max_length=50)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, help_text='Date the invoice was issued')),
                ('due_date', models.DateField(help_text='Date payment is due')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status of the invoice', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of services or period covered')),
                ('services_start_date', models.DateField(blank=True, help_text='Start date of services covered by this invoice', null=True)),
                ('services_end_date', models.DateField(blank=True, help_text='End date of services covered by this invoice', null=True)),
                ('child', models.ForeignKey(help_text='Child this invoice is for', on_delete=django.db.models.deletion.CASCADE, to='daycare_invoices.child')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
                ('provider', models.ForeignKey(help_text='Daycare provider who issued the invoice', on_delete=django.db.models.deletion.CASCADE, to='daycare_invoices.daycareprovider')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment was made')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('other', 'Other')], default='cash', help_text='Payment method used', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('family', models.ForeignKey(help_text='Family this record belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, to='daycare_invoices.invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
