# Generated by Django 5.2.6 on 2025-10-08 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, help_text='Whether the user is currently online')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time the user was active')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last heartbeat timestamp from WebSocket connection', null=True)),
                ('current_page', models.CharField(blank=True, help_text='Current page/module the user is viewing', max_length=200, null=True)),
                ('channel_name', models.CharField(blank=True, help_text='WebSocket channel name for active connection', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User whose presence is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user presences',
                'ordering': ['-last_seen'],
            },
        ),
    ]
