# Generated by Django 5.2.5 on 2025-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('root', 'Root Account'), ('income', 'Income Account'), ('expense', 'Expense Account')], help_text='Type of account: root, income, or expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what this account is for'),
        ),
    ]
