# Generated by Django 5.2.5 on 2025-09-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_allocation', '0002_alter_account_account_type_alter_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='week',
            field=models.ForeignKey(blank=True, help_text='Week this transaction belongs to (auto-assigned if not specified)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_transactions', to='budget_allocation.weeklyperiod'),
        ),
    ]
