# Generated by Django 5.2.5 on 2025-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_allocation', '0003_alter_transaction_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_merchant_payee',
            field=models.BooleanField(default=False, help_text='Whether this account represents a merchant/payee for transactions'),
        ),
    ]
