# Generated by Django 5.2.5 on 2025-09-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_allocation', '0004_account_is_merchant_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the transaction', max_length=200),
        ),
    ]
