# Generated by Django 5.2.5 on 2025-09-04 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Company name', max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, help_text='Industry sector', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Company location (city, state/country)', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('description', models.TextField(blank=True, help_text='Company description')),
                ('size', models.CharField(blank=True, help_text='Company size (e.g., 1-10, 11-50, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Skill name', max_length=100, unique=True)),
                ('category', models.CharField(help_text='Skill category (e.g., Programming, Design, Management)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Skill description')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(help_text='Educational institution name', max_length=200)),
                ('degree', models.CharField(help_text='Degree or certification obtained', max_length=100)),
                ('field_of_study', models.CharField(blank=True, help_text='Field of study or major', max_length=100)),
                ('start_date', models.DateField(help_text='Start date of education')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if ongoing)', null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='GPA (if applicable)', max_digits=3, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about education')),
                ('is_current', models.BooleanField(default=False, help_text='Whether currently pursuing this education')),
                ('user', models.ForeignKey(help_text='User this record belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('start_date', models.DateField(help_text='Start date of employment')),
                ('end_date', models.DateField(blank=True, help_text='End date of employment (leave blank if current)', null=True)),
                ('description', models.TextField(blank=True, help_text='Job description and responsibilities')),
                ('salary_range', models.CharField(blank=True, help_text='Salary range (e.g., $50,000 - $60,000)', max_length=100)),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is a current position')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', help_text='Type of employment', max_length=50)),
                ('achievements', models.TextField(blank=True, help_text='Key achievements and accomplishments')),
                ('reason_for_leaving', models.TextField(blank=True, help_text='Reason for leaving (if applicable)')),
                ('supervisor_name', models.CharField(blank=True, help_text='Name of supervisor/manager', max_length=100)),
                ('supervisor_contact', models.CharField(blank=True, help_text='Supervisor contact information', max_length=200)),
                ('company', models.ForeignKey(help_text='Company where position was held', on_delete=django.db.models.deletion.CASCADE, to='employment_history.company')),
                ('user', models.ForeignKey(help_text='User this record belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PositionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Proficiency level for this skill', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience with this skill', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about skill usage')),
                ('position', models.ForeignKey(help_text='Position where skill was used', on_delete=django.db.models.deletion.CASCADE, to='employment_history.position')),
                ('skill', models.ForeignKey(help_text='Skill used in this position', on_delete=django.db.models.deletion.CASCADE, to='employment_history.skill')),
            ],
            options={
                'verbose_name': 'Position Skill',
                'verbose_name_plural': 'Position Skills',
                'ordering': ['skill__category', 'skill__name'],
                'unique_together': {('position', 'skill')},
            },
        ),
    ]
