# Generated by Django 5.2.5 on 2025-10-02 01:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text="Unique identifier for the model (e.g., 'email_daycare_classifier')", max_length=100)),
                ('model_version', models.CharField(help_text="Semantic version (e.g., '1.0.0', '2.1.3')", max_length=20)),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('ranking', 'Ranking'), ('other', 'Other')], default='classification', max_length=20)),
                ('model_file', models.FileField(help_text='Pickled model file (scikit-learn, joblib, etc.)', upload_to='ai/models/')),
                ('vectorizer_file', models.FileField(blank=True, help_text='Pickled vectorizer/transformer (if applicable)', null=True, upload_to='ai/vectorizers/')),
                ('feature_config', models.JSONField(default=dict, help_text='Feature extraction configuration and settings')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Accuracy, precision, recall, F1, confusion matrix, etc.')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Currently deployed/active model version')),
                ('training_samples_count', models.IntegerField(default=0, help_text='Number of samples used for training')),
                ('description', models.TextField(blank=True, help_text='Model description, notes, changes from previous version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the predicted object')),
                ('predicted_label', models.CharField(db_index=True, help_text='AI-predicted classification', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Prediction confidence (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('all_predictions', models.JSONField(default=dict, help_text='All class probabilities {class: probability}')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed by User'), ('rejected', 'Rejected by User'), ('ignored', 'Ignored'), ('auto_applied', 'Auto-Applied')], db_index=True, default='pending', max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When user reviewed this prediction', null=True)),
                ('feedback_note', models.TextField(blank=True, help_text='User feedback or correction notes')),
                ('correct_label', models.CharField(blank=True, help_text='Correct label if prediction was rejected', max_length=50)),
                ('content_type', models.ForeignKey(help_text='Type of object this prediction is for', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai.mlmodel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Prediction',
                'verbose_name_plural': 'AI Predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(help_text='Descriptive name for this dataset', max_length=200)),
                ('model_name', models.CharField(db_index=True, help_text="Associated model name (e.g., 'email_daycare_classifier')", max_length=100)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Selection'), ('user_feedback', 'User Feedback'), ('imported', 'Imported Dataset'), ('auto_labeled', 'Auto-Labeled'), ('active_learning', 'Active Learning')], default='manual', max_length=20)),
                ('total_samples', models.IntegerField(default=0, help_text='Total number of samples in this dataset')),
                ('positive_samples', models.IntegerField(default=0, help_text='Number of positive class samples')),
                ('negative_samples', models.IntegerField(default=0, help_text='Number of negative class samples')),
                ('is_processed', models.BooleanField(default=False, help_text='Has this dataset been used for training')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Dataset notes, collection method, quality notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Dataset',
                'verbose_name_plural': 'Training Datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_identifier', models.CharField(help_text='Human-readable identifier (e.g., email subject)', max_length=200)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the referenced object')),
                ('features', models.JSONField(default=dict, help_text='Extracted features for this sample')),
                ('label', models.CharField(db_index=True, help_text='Ground truth label/classification', max_length=50)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence if from AI prediction (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('manual', 'Manual Label'), ('ai_confirmed', 'AI Prediction Confirmed'), ('ai_rejected', 'AI Prediction Rejected'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this sample')),
                ('content_type', models.ForeignKey(help_text='Type of object this sample references', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_samples', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='ai.trainingdataset')),
            ],
            options={
                'verbose_name': 'Training Sample',
                'verbose_name_plural': 'Training Samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_name', 'is_active'], name='ai_mlmodel_model_n_ad460a_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_type', 'is_active'], name='ai_mlmodel_model_t_76e995_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('model_name', 'model_version')},
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['content_type', 'object_id'], name='ai_predicti_content_7d1bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['status', 'confidence_score'], name='ai_predicti_status_216a56_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model', 'status'], name='ai_predicti_model_i_d71897_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdataset',
            index=models.Index(fields=['model_name', 'is_processed'], name='ai_training_model_n_83167e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsample',
            index=models.Index(fields=['content_type', 'object_id'], name='ai_training_content_57f4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsample',
            index=models.Index(fields=['label', 'source'], name='ai_training_label_e24c6c_idx'),
        ),
    ]
