# Generated by Django 5.2.5 on 2025-10-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_invoiceextraction_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceextraction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Child/customer reference number (e.g., SG300)', max_length=100),
        ),
    ]
