# Generated by Django 5.2.5 on 2025-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_invoiceextraction_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceextraction',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='List of invoice line items: [{"type": "debit|credit|previous_balance|discount", "description": "", "amount": 0.00}]'),
        ),
    ]
