# Generated by Django 5.2.5 on 2025-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_invoiceextraction_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceextraction',
            name='current_invoice_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current invoice charges only (excluding previous balance)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceextraction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount due (including previous balance)', max_digits=10, null=True),
        ),
    ]
